# Generated by Django 3.1.1 on 2020-09-21 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200921_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
