# Generated by Django 3.1.1 on 2020-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200921_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
    ]
