# Generated by Django 3.1.1 on 2020-09-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200921_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bizcategory',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
