# Generated by Django 3.1.1 on 2020-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_bizcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bizimage',
            field=models.ImageField(blank=True, default='media/bonobono.png', null=True, upload_to='biz'),
        ),
    ]
