# Generated by Django 3.1.1 on 2020-09-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
            ],
        ),
    ]
